### ISSUE TITLE
Fails with misleading message for models that don't define lkerf, lidentify, and lmargin

### ISSUE THREAD

**Issue by cbiffle** [mbugert/laserscad#14]
I've spent a couple days trying to debug OpenSCAD's import behavior, when it turned out to be a problem with laserscad.

Laserscad prints the following failure message if *any warnings* come out of OpenSCAD in from `laserscad.scad`:

```text
Error: OpenSCAD cannot find 'laserscad.scad'. Put 'laserscad.scad' in the OpenSCAD libraries folder or in the same folder as your model.
```

That statement is incorrect. In my case, the warnings were

```text
WARNING: Ignoring unknown variable 'lkerf', in file laserscad.scad, line 150.
WARNING: Ignoring unknown variable 'lmargin', in file laserscad.scad, line 151.
WARNING: Ignoring unknown variable 'lidentify', in file laserscad.scad, line 152.
```

As a workaround, defining all three variables in my design silences the warnings.

**Comment by mbugert** [comment]
Thanks for reporting, this was fixed by @jmgao.
